[workspace]
members = [
    "blobby",
    "block-buffer",
    "block-padding",
    "byte-tools",
    "collectable",
    "dbl",
    "fake-simd",
    "hex-literal",
    "hex-literal/hex-literal-impl",
    "opaque-debug",
]
