[workspace]
resolver = "3"
members = [
    "blobby",
    "block-buffer",
    "block-padding",
    "collectable",
    "cmov",
    "ctutils",
    "cpufeatures",
    "dbl",
    "digest-io",
    "hex-literal",
    "inout",
    "opaque-debug",
    "wycheproof2blb",
    "zeroize",
    "zeroize_derive"
]
exclude = ["aarch64-dit"]

[profile.dev]
opt-level = 2

[patch.crates-io]
cmov = { path = "cmov" }
