[workspace]
resolver = "2"
members = [
    "algorithm-registry",
    "blobby",
    "block-buffer",
    "block-padding",
    "collectable",
    "cmov",
    "cpufeatures",
    "dbl",
    "fiat-constify",
    "hex-literal",
    "hybrid-array",
    "inout",
    "opaque-debug",
    "wycheproof2blb",
    "zeroize",
    "zeroize/derive",
]

[profile.dev]
opt-level = 2

[patch.crates-io]
crypto-common = { git = "https://github.com/RustCrypto/traits" }
