[package]
name = "wycheproof2blb"
version = "0.1.0" # Also update html_root_url in lib.rs when bumping this
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "A utility for converting Wycheproof test vectors to the blobby format"
repository = "https://github.com/RustCrypto/utils"
keywords = ["test", "Wycheproof"]
categories = ["cryptography", "no-std"]
edition = "2018"

[dependencies]
blobby = { version = "0.3.1", path = "../blobby" }
hex = "0.4"
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1"
