[package]
name = "wycheproof2blb"
version = "0.2.0-pre"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "A utility for converting Wycheproof test vectors to the blobby format"
repository = "https://github.com/RustCrypto/utils"
keywords = ["test", "Wycheproof"]
categories = ["cryptography", "no-std"]
edition = "2024"
rust-version = "1.85"

[dependencies]
blobby = { version = "0.4.0-pre", path = "../blobby", features = ["alloc"] }
hex = "0.4"
serde = { version = "1.0.184", features = ["derive"] }
serde_json = "1"
