[package]
name = "zeroize_derive"
version = "1.5.0"
authors = ["The RustCrypto Project Developers"]
edition = "2024"
rust-version = "1.85"
documentation = "https://docs.rs/zeroize_derive"
readme = "README.md"
repository = "https://github.com/RustCrypto/utils"
license = "Apache-2.0 OR MIT"
keywords = ["memory", "memset", "secure", "volatile", "zero"]
categories = ["cryptography", "memory-management", "no-std", "os"]
description = "Custom derive support for zeroize"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits", "visit"] }

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--document-private-items"]
