[package]
name = "der_derive"
version = "0.4.0" # Also update html_root_url in lib.rs when bumping this
description = """
Procedural macro for automatically deriving the `der` crate's `Choice` and
`Message` traits
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
edition = "2018"
documentation = "https://docs.rs/der"
repository = "https://github.com/RustCrypto/utils/tree/master/der"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords = ["asn1", "der", "crypto", "itu", "pkcs"]
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "1"
synstructure = "0.12"
