[package]
name = "inout"
version = "0.2.2"
authors = ["RustCrypto Developers"]
edition = "2024"
rust-version = "1.85"
documentation = "https://docs.rs/inout"
readme = "README.md"
repository = "https://github.com/RustCrypto/utils"
license = "MIT OR Apache-2.0"
keywords = ["custom-reference"]
categories = ["no-std"]
description = "Custom reference types for code generic over in-place and buffer-to-buffer modes of operation."

[dependencies]
hybrid-array = "0.4"
block-padding = { version = "0.4.2", path = "../block-padding", optional = true }

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
