[package]
name = "block-buffer"
version = "0.11.0-pre"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Buffer type for block processing of data"
documentation = "https://docs.rs/block-buffer"
repository = "https://github.com/RustCrypto/utils"
keywords = ["block", "buffer"]
categories = ["cryptography", "no-std"]
edition = "2021"
readme = "README.md"

[dependencies]
crypto-common = "0.2.0-pre"
generic-array = "0.14"

[dev-dependencies]
hex-literal = "0.3.3"
