[package]
name = "simd-buffers"
version = "0.0.0" # Also update html_root_url in lib.rs when bumping this
description = """
SIMD buffer types
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
edition = "2018"
documentation = "https://docs.rs/simd-buffers"
repository = "https://github.com/RustCrypto/utils/tree/master/simd-buffers"
categories = ["cryptography", "data-structures"]
keywords = ["simd"]
readme = "README.md"

[dependencies]
cfg-if = "1"

[features]
force-soft = []
