[package]
name = "opaque-debug"
version = "0.4.0-pre"
authors = ["RustCrypto Developers"]
edition = "2024"
rust-version = "1.85"
documentation = "https://docs.rs/opaque-debug"
readme = "README.md"
repository = "https://github.com/RustCrypto/utils"
license = "MIT OR Apache-2.0"
description = "Macro for opaque Debug trait implementation"

[lints]
workspace = true
