[package]
name = "hybrid-array"
version = "0.2.0-pre.5"
description = """
Hybrid typenum-based and const generic array types designed to provide the
flexibility of typenum-based expressions while also allowing interoperability
and a transition path to const generics
"""
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/hybrid-array"
repository = "https://github.com/RustCrypto/utils/tree/master/hybrid-array"
categories = ["no-std", "data-structures"]
keywords = ["generic-array"]
readme = "README.md"
edition = "2021"
rust-version = "1.65"

[dependencies]
typenum = "1.17"
serde = { version = "1", optional = true }

[dev-dependencies]
bincode = "1.3"
serde_json = "1"

[features]
default = []
serde = ["dep:serde"]
