[package]
name = "x509"
version = "0.0.0" # Also update html_root_url in lib.rs when bumping this
description = """
Pure Rust implementation of the X.509 Public Key Infrastructure Certificate
format as described in RFC 5280
"""
authors    = ["RustCrypto Developers"]
license    = "Apache-2.0 OR MIT"
edition    = "2018"
repository = "https://github.com/RustCrypto/utils/tree/master/x509"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords   = ["crypto", "x.509"]
readme     = "README.md"

[dependencies]
der = { version = "0.4", features = ["derive"], path = "../der" }
spki = { version = "0.4", path = "../spki" }

[features]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
