[package]
name = "dbl"
version = "0.3.2" # Also update html_root_url in lib.rs when bumping this
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Double operation in Galois Field (GF)"
documentation = "https://docs.rs/dbl"
repository = "https://github.com/RustCrypto/utils"
keywords = ["crypto", "dbl", "gf", "galois"]

[dependencies]
generic-array = "0.14"
