[package]
name = "dbl"
version = "0.4.0-pre"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Double operation in Galois Field (GF)"
documentation = "https://docs.rs/dbl"
repository = "https://github.com/RustCrypto/utils"
keywords = ["crypto", "dbl", "gf", "galois"]
edition = "2021"
rust-version = "1.65"

[dependencies]
hybrid-array = "=0.2.0-pre.6"
